### ISSUE TITLE
vagrant up craps out if path to pubstack has spaces or "(", etc... 

### ISSUE THREAD

**Issue by bleen** [NBCUTechnology/pubstack#108]
see: http://bit.ly/1oHp8IN

/Users/bleen/Cloud/Dropbox (Personal)/Sites/pubstack/provisioning
...should be escaped to: 
/Users/bleen/Cloud/Dropbox\ (Personal)/Sites/pubstack/provisioning/

**Comment by rabellamy** [comment]
See #194
