### ISSUE TITLE
Performance Tools & Docs

### ISSUE THREAD

**Issue by ericduran** [NBCUTechnology/pubstack#109]
- [ ] Document xhprof availability
- [ ] Document siege availability
- [ ] Document profiling with xhprof
- [ ] Document profiling with xdebug
- [ ] Document tracing with xdebug
- [ ] Document how to see mysql slow query logs
- [ ] Add webgrind
- [ ] Add XHGui
- [x] Add local splunk for logs gathering

**Comment by rabellamy** [comment]
See #194
