### ISSUE TITLE
Remove ubuntu's 'do-release-upgrade' msg on ssh login

### ISSUE THREAD

**Issue by jpklein** [NBCUTechnology/pubstack#117]
_From Slack_:

> jpklein [11:29]
> @channel: when I ssh into my ubuntu, it's telling me:
> New release '14.04.1 LTS' available. Run 'do-release-upgrade' to upgrade to it
> should I do it?
> 
> elijahlynn [11:29] 
> jpklein: no, you need to stay at Acquia's version
> but they should disable that message/check they = scottrigby && ericduran
> 
> ericduran [11:30] 
> jpklein: Yea we want the current version because of acquia
> 
> ericduran [11:30]
> @elijahlynn: PR to remove that message!!!

**Bonus Points**: Replace the current message with one explaining not to update ubuntu or its packages in order to maintain parity with Acquia.

**Comment by rabellamy** [comment]
See #194
