### ISSUE TITLE
Fixing php-fpm settings

### ISSUE THREAD

**Issue by ericduran** [NBCUTechnology/pubstack#127]
We need to update our php.ini since it's still missing some settings.

quick list from the new env set up I did: 
 realpath_cache_size, request_order , short_open_tag, variables_order, date.timezone, MongoDB Support,  MSSQL Support, mysqlnd, pdo_pgsql, readline, session.entropy_file (acquia sets this to nothing, I think /dev/urandom makes more sense). opcode Optimization, opcache.enable_cli, opcache.fast_shutdown, opcache.interned_strings_buffer

**Comment by rabellamy** [comment]
See #194
