### ISSUE TITLE
Merge Ubuntu settings into the centos branch

### ISSUE THREAD

**Issue by scottrigby** [NBCUTechnology/pubstack#137]
Sometime checkout the centos/amazonlinux branches (the same, just with different base boxes & box names). The main good thing those branches do though is split up the configs by os and distribution (more like jeff geerling's code, in fact a lot but not all is borrowed from his roles). 

The other big benefit from this is we can use that branch of pubstack to deploy directly to servers as well as run on our local box. Big win.

The thing we need to do now is merge the Ubuntu configs (and some of the PRs that got in after i started working on the centos branch) from the master branch into the now genericized centos one, and make that the new master.

**Comment by rabellamy** [comment]
See #194
