### ISSUE TITLE
Move Database creation outside of mysql role

### ISSUE THREAD

**Issue by ericduran** [NBCUTechnology/pubstack#150]
Right now we have:

```
- name: create site database
  mysql_db: name={{ item.shortname }} state=present collation=utf8_general_ci
  with_items: sites
  when: sites is defined

- name: create database user
  mysql_user: name={{ item.shortname }} password= priv={{ item.shortname }}.*:ALL host=% state=present
  with_items: sites
  when: sites is defined
```

This should be in the drupal role. This came up when running the percona stuff on the CI boxes I don't do the drupal role but this still ran, which is fine just probably shouldn't be there.

**Comment by cweagans** [comment]
Homestead solves this by having database creation outside of the provisioning scripts, which I'm rather fond of, as it only requires a `vagrant reload`, rather than a `vagrant provision`. It would move us in the direction of being able to package a base box, too.

**Comment by rabellamy** [comment]
See #194
