### ISSUE TITLE
Create a creds.json file for DB configs (so AWS can mimic Acquia)

### ISSUE THREAD

**Issue by richburke-nbc** [NBCUTechnology/pubstack#157]
SimpleSAML needs the DB credentials so it can write values to the users & authmap tables.   In Publisher SSO, for non-local environments, we read these values from a creds.json file (/var/www/site-php/<AH_SITE_NAME>/creds.json).   Well, this is true on Acquia servers.    On AWS servers we don't have a method for retrieving that info.

It would be cool if we could create such a file if it doesn't already exist so we can pull this information in a consistent manner.

**Comment by rabellamy** [comment]
See #194
