### ISSUE TITLE
Add Varnish 3.0

### ISSUE THREAD

**Issue by xopoc14** [NBCUTechnology/pubstack#177]

**Comment by cweagans** [comment]
Is Acquia running Varnish 3.x or 4.x?

**Comment by ElijahLynn** [comment]
@scottrigby @ericduran Do you guys know what version of Varnish Acquia is using?

**Comment by ericduran** [comment]
I haven't work with acquia in over a year, back then it was 3.x no clue about now.

**Comment by scottrigby** [comment]
See #194.
