### ISSUE TITLE
Failed to install drush: "msg: unsupported parameter for module: command"

### ISSUE THREAD

**Issue by sergesemashko** [NBCUTechnology/pubstack#189]
I have the following error on attempt to create new machine:
```bash
TASK: [drush | install drush dependencies with composer] ********************** 
failed: [dev] => {"failed": true}
msg: unsupported parameter for module: command

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/siarheisemashka/pubstack.retry

dev                        : ok=55   changed=4    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Not 100% sure where are the roots of the issue, but after reverting `pubstack/provisioning/roles/drush/tasks/main.yml` to [51a941a347c72b7553e840f1f012b7845d5b8120](https://github.com/NBCUTechnology/pubstack/blob/8ba6743353f46fdb41381222fa5914ca0b6cab2d/provisioning/roles/drush/tasks/main.yml) I was able to install drush. Compare to [latest code](https://github.com/NBCUTechnology/pubstack/blob/master/provisioning/roles/drush/tasks/main.yml)

@conortm @ericduran @cweagans, any suggestions? 
Does anyone else have this issue at all on local?

**Comment by cweagans** [comment]
What version of Ansible are you on?

**Comment by sergesemashko** [comment]
that was on 1.7.1, the issue is gone on 1.9.2. false alarm :frog: 
@cweagans thanks

**Comment by cweagans** [comment]
:+1: No problem
