### ISSUE TITLE
Switch to ansible_local provisioner

### ISSUE THREAD

**Issue by cweagans** [NBCUTechnology/pubstack#192]
https://docs.vagrantup.com/v2/provisioning/ansible_local.html

Removes the need to install Ansible on the host.

**Comment by scottrigby** [comment]
@cweagans you had a version of this working, right? I still like this idea. What is the downside (provisioning time etc)?

**Comment by cweagans** [comment]
I had a hacky version of this at one point. It was installing Ansible manually and then running `ansible-playbook` with the shell provisioner. This is the official way to do it, and functions similarly to how the Chef/Puppet provisioners work. I don't think there's a downside here - Pubstack should provision just as quickly.

I think the change might be as simple as changing [this line](https://github.com/NBCUTechnology/pubstack/blob/master/Vagrantfile#L122) to this: `dev.vm.provision 'ansible_local' do |ansible|`.

**Comment by scottrigby** [comment]
Cool idea, but here's a better one. See #194. 😉
