### ISSUE TITLE
Acquia parity

### ISSUE THREAD

**Issue by conortm** [NBCUTechnology/pubstack#2]
- [x] Match versions/configs:
  - [x] Distro: Linux 2.6.32-351-ec2 #63-Ubuntu SMP x86_64 GNU/Linux
  - [x] Apache
  - [x] PHP: 5.5.11 (FPM)
  - [x] MySQL
  - [x] Extensions/packages (i.e. xdebug, xhprof)
- [ ] Varnish (#32, #35)
- [ ] Match env architecture (multiple VM's) (#32, #35)

**Comment by rabellamy** [comment]
See #194
