### ISSUE TITLE
Do we want to switch a chunk of the provisioning to a base box before release?

### ISSUE THREAD

**Issue by ericduran** [NBCUTechnology/pubstack#62]
After reading a lot of vagrant base blogs,

a lot of them recomend doing base boxes instead of just provision.

The nice thing about the base box is:
- we can version it
- Fast provisioning, since all the downloads, etc. will already be there
- we don't need to worry about provisioning errors, besides the site portion of it, but that's mostly working on the vagrant image.
- easy to push update since we can have the base box be a public available link, so pushing update is as easy as release a new box version.

**Comment by rabellamy** [comment]
See #194
